apiVersion: harness.io/v1
kind: Component
type: service
identifier: my_new_service
name: my-new-service
owner: group:account/_account_all_users
orgIdentifier: testautoidp
projectIdentifier: testautoidp
spec:
  lifecycle: production
  sourceCode:
    provider: Harness
    repoName: idp-deo-repo
    connectorRef: github_connector1
    branch: main
    monoRepo: false
    url: https://github.com/divyashreehs15/idp-demo-repo
metadata:
  tags:
    - project
  annotations:
    harness.io/pipelines: |
      CI: <your_pipeline_full_url>
