apiVersion: harness.io/v1
kind: Component
identifier: harnessenv2
name: harness-env2
type: service
owner: group:account/_account_all_users
orgIdentifier: testautoidp
projectIdentifier: testautoidp
spec:
  lifecycle: production
  sourceCode:
    provider: Harness
    repoName: idp-demo-repo
    connectorRef: github-connector1
    branch: main
    monoRepo: false
    url: https://github.com/divyashreehs15/idp-demo-repo
metadata:
  description: ""
  tags:
    - project
    - harness
    - data
  annotations:
    harness.io/pipelines: |
      CI: <your_pipeline_full_url>
