apiVersion: harness.io/v1
kind: Component
type: service
identifier: harnessenv2
name: harness-env2
owner: group:account/AAAFF
spec:
  lifecycle: production
metadata:
  description: Harness Docs update
  annotations:
    github.com/project-slug: divyashreehs15/idp-demo-repo
  tags:
  - project
  - react
