apiVersion: harness.io/v1
kind: Component
identifier: harnessenv2
name: harness-env2
type: service
owner: group:account/_account_all_users
orgIdentifier: testautoidp
projectIdentifier: testautoidp
spec:
  lifecycle: production
  sourceCode:
    provider: Harness
    repoName: your-repo-name
    connectorRef: your_github_connector_identifier
    branch: main
    monoRepo: false
    url: https://github.com/your-username/your-repo-name
metadata:
  description: ""
  tags:
    - project
    - harness
    - data
  annotations:
    harness.io/pipelines: |
      CI: <your_pipeline_full_url>
