apiVersion: harness.io/v1
kind: Workflow
identifier: hello_workflow
name: Hello Workflow
type: service
spec:
  owner: group:account/_account_all_users
  parameters:
    - title: Your Info
      required:
        - name
      properties:
        name:
          type: string
          title: Your Name
          description: Enter your name
  steps:
    - id: say-hello
      name: Say Hello
      action: harness:pipeline:run
      input:
        url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/module/idp-admin/orgs/default/projects/artistreact1/pipelines/creategithubrepo/pipeline-studio/?storeType=INLINE
        inputset:
          name: ${{ parameters.name }}
